import type { Event } from "@/types";

export const initialEvents: Event[] = [
  {
    id: 1,
    title: "Team Standup",
    description: "Daily team synchronization meeting",
    date: "2025-07-08",
    startTime: "09:00",
    endTime: "09:30",
    location: "Conference Room A",
    type: "meeting",
    organizer: "Sarah Johnson",
    attendees: ["John Doe", "Mike Wilson", "Sarah Johnson"],
    department: "Sales",
    isPrivate: false,
    color: "blue",
  },
  {
    id: 2,
    title: "Q1 Budget Review",
    description: "Quarterly budget analysis and planning session",
    date: "2025-07-18",
    startTime: "14:00",
    endTime: "16:00",
    location: "Boardroom",
    type: "presentation",
    organizer: "Management",
    attendees: ["Managers", "Finance Team"],
    department: "Finance",
    isPrivate: true,
    color: "red",
  },
  {
    id: 3,
    title: "System Maintenance",
    description: "Scheduled server maintenance and updates",
    date: "2025-08-10",
    startTime: "02:00",
    endTime: "04:00",
    location: "Server Room",
    type: "maintenance",
    organizer: "IT Department",
    attendees: ["IT Team"],
    department: "IT",
    isPrivate: false,
    color: "orange",
  },
  {
    id: 4,
    title: "Company All-Hands",
    description: "Monthly company-wide meeting",
    date: "2025-08-15",
    startTime: "10:00",
    endTime: "11:30",
    location: "Main Hall",
    type: "presentation",
    organizer: "Administrator",
    attendees: ["All Employees"],
    department: "General",
    isPrivate: false,
    color: "green",
  },
];
