import type { Officer } from "@/types";

export const initialOfficers: Officer[] = [
  //   Level
  {
    id: 1,
    name: "Robert Johnson",
    position: "Admin",
    department: "Executive",
    email: "robert.johnson@company.com",
    phone: "+1 (555) 001-0001",
    avatar: "/api/placeholder/64/64",
    joinDate: "2018-01-15",
    directReports: 4,
    status: "active",
  },

  // SVP Level
  {
    id: 2,
    name: "Sarah Williams",
    position: "SVP",
    department: "Operations",
    email: "sarah.williams@company.com",
    phone: "+1 (555) 002-0002",
    avatar: "/api/placeholder/64/64",
    joinDate: "2019-03-20",
    reportingTo: "Robert Johnson",
    directReports: 3,
    status: "active",
  },
  {
    id: 3,
    name: "Michael Chen",
    position: "SVP",
    department: "Technology",
    email: "michael.chen@company.com",
    phone: "+1 (555) 003-0003",
    avatar: "/api/placeholder/64/64",
    joinDate: "2019-06-10",
    reportingTo: "Robert Johnson",
    directReports: 4,
    status: "active",
  },
  {
    id: 4,
    name: "Emily Davis",
    position: "SVP",
    department: "Finance",
    email: "emily.davis@company.com",
    phone: "+1 (555) 004-0004",
    avatar: "/api/placeholder/64/64",
    joinDate: "2020-01-08",
    reportingTo: "Robert Johnson",
    directReports: 2,
    status: "active",
  },

  // VP Level
  {
    id: 5,
    name: "David Wilson",
    position: "VP",
    department: "Sales",
    email: "david.wilson@company.com",
    phone: "+1 (555) 005-0005",
    avatar: "/api/placeholder/64/64",
    joinDate: "2020-04-15",
    reportingTo: "Sarah Williams",
    directReports: 5,
    status: "active",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    position: "VP",
    department: "Marketing",
    email: "lisa.anderson@company.com",
    phone: "+1 (555) 006-0006",
    avatar: "/api/placeholder/64/64",
    joinDate: "2020-07-22",
    reportingTo: "Sarah Williams",
    directReports: 4,
    status: "active",
  },
  {
    id: 7,
    name: "James Rodriguez",
    position: "VP",
    department: "Engineering",
    email: "james.rodriguez@company.com",
    phone: "+1 (555) 007-0007",
    avatar: "/api/placeholder/64/64",
    joinDate: "2021-02-10",
    reportingTo: "Michael Chen",
    directReports: 8,
    status: "active",
  },
  {
    id: 8,
    name: "Maria Garcia",
    position: "VP",
    department: "HR",
    email: "maria.garcia@company.com",
    phone: "+1 (555) 008-0008",
    avatar: "/api/placeholder/64/64",
    joinDate: "2021-05-18",
    reportingTo: "Sarah Williams",
    directReports: 3,
    status: "active",
  },

  // Officer Level
  {
    id: 9,
    name: "John Smith",
    position: "Officer",
    department: "Sales",
    email: "john.smith@company.com",
    phone: "+1 (555) 009-0009",
    avatar: "/api/placeholder/64/64",
    joinDate: "2021-08-12",
    reportingTo: "David Wilson",
    directReports: 6,
    status: "active",
  },
  {
    id: 10,
    name: "Jennifer Brown",
    position: "Officer",
    department: "Marketing",
    email: "jennifer.brown@company.com",
    phone: "+1 (555) 010-0010",
    avatar: "/api/placeholder/64/64",
    joinDate: "2021-11-03",
    reportingTo: "Lisa Anderson",
    directReports: 4,
    status: "active",
  },
  {
    id: 11,
    name: "Thomas Lee",
    position: "Officer",
    department: "Engineering",
    email: "thomas.lee@company.com",
    phone: "+1 (555) 011-0011",
    avatar: "/api/placeholder/64/64",
    joinDate: "2022-01-20",
    reportingTo: "James Rodriguez",
    directReports: 5,
    status: "active",
  },
  {
    id: 12,
    name: "Amanda Taylor",
    position: "Officer",
    department: "Finance",
    email: "amanda.taylor@company.com",
    phone: "+1 (555) 012-0012",
    avatar: "/api/placeholder/64/64",
    joinDate: "2022-03-15",
    reportingTo: "Emily Davis",
    directReports: 3,
    status: "active",
  },

  // Staff Level
  {
    id: 13,
    name: "Kevin Johnson",
    position: "Employee",
    department: "Sales",
    email: "kevin.johnson@company.com",
    phone: "+1 (555) 013-0013",
    avatar: "/api/placeholder/64/64",
    joinDate: "2022-06-08",
    reportingTo: "John Smith",
    directReports: 0,
    status: "active",
  },
];
