import type { Announcement } from "@/types";

export const initialAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "System Maintenance Scheduled",
    content:
      "We will be performing system maintenance on Sunday, March 10th from 2:00 AM to 4:00 AM. During this time, the system will be unavailable.",
    author: "IT Department",
    department: "IT",
    priority: "high",
    pinned: true,
    date: "2025-07-10",
    views: 145,
    likes: 12,
    comments: 3,
    tags: ["maintenance", "system"],
    readBy: [],
    viewers: [
      {
        userId: 1,
        name: "John Doe",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-07-10 09:15",
        department: "Sales",
        role: "VP",
      },
      {
        userId: 2,
        name: "Sarah Johnson",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-07-10 09:30",
        department: "Marketing",
        role: "Officer",
      },
    ],
  },
  {
    id: 2,
    title: "New Employee Welcome",
    content:
      "Please join us in welcoming Sarah Johnson to the Marketing team. She will be starting as a Marketing Specialist on Monday.",
    author: "HR Department",
    department: "HR",
    priority: "medium",
    pinned: false,
    date: "2025-05-15",
    views: 89,
    likes: 25,
    comments: 8,
    tags: ["welcome", "team"],
    readBy: [],
    viewers: [
      {
        userId: 1,
        name: "John Doe",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-05-15 10:15",
        department: "Sales",
        role: "SVP",
      },
      {
        userId: 2,
        name: "Sarah Johnson",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-05-15 10:30",
        department: "Marketing",
        role: "Officer",
      },
      {
        userId: 3,
        name: "Michael Chen",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-05-15 10:45",
        department: "Engineering",
        role: "Officer",
      },
      {
        userId: 4,
        name: "Emily Brown",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-05-15 11:00",
        department: "Sales",
        role: "Officer",
      },
    ],
  },
  {
    id: 3,
    title: "Q1 Company Meeting",
    content:
      "The quarterly company meeting is scheduled for March 15th at 10:00 AM in the main conference room. Attendance is mandatory for all employees.",
    author: "Management",
    department: "Management",
    priority: "high",
    pinned: true,
    date: "2025-07-19",
    views: 203,
    likes: 18,
    comments: 5,
    tags: ["meeting", "quarterly"],
    readBy: [],
    viewers: [
      {
        userId: 1,
        name: "John Doe",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-07-19 11:00",
        department: "Sales",
        role: "Officer",
      },
    ],
  },
  {
    id: 4,
    title: "Office Lunch Event",
    content:
      "Join us for a catered lunch event next Friday at 12:00 PM. Please RSVP by Wednesday to help us plan accordingly.",
    author: "Social Committee",
    department: "General",
    priority: "low",
    pinned: false,
    date: "2025-07-20",
    views: 156,
    likes: 45,
    comments: 12,
    tags: ["social", "lunch"],
    readBy: [],
    viewers: [
      {
        userId: 1,
        name: "John Doe",
        avatar: "/api/placeholder/32/32",
        readAt: "2025-07-20 11:00",
        department: "Sales",
        role: "Officer",
      },
    ],
  },
];

export const departments = [
  "Departemen Produksi",
  "Departemen Pemeliharaan (Maintenance)",
  "Departemen Kesehatan, Keselamatan Kerja dan Lingkungan (K3LH)",
  "Departemen Pemasaran dan Penjualan",
  "Departemen Logistik dan Distribusi",
  "Departemen Riset dan Pengembangan (R&D)",
  "Departemen Keuangan dan Akuntansi",
  "Departemen Sumber Daya Manusia (SDM) dan Umum",
  "Departemen Teknologi Informasi (TI/IT)",
];
