import type { Document } from "@/types";

export const initialDocuments: Document[] = [
  {
    id: 1,
    name: "Q4_Financial_Report.pdf",
    type: "pdf",
    size: "2.4 MB",
    uploadedBy: "John Smith",
    uploadDate: "2025-05-08",
    accessLevel: "Administrator",
    department: "Finance",
    downloads: 45,
    views: 120,
    shared: true,
  },
  {
    id: 2,
    name: "Marketing_Strategy_2024.docx",
    type: "document",
    size: "1.8 MB",
    uploadedBy: "Sarah Johnson",
    uploadDate: "2025-07-07",
    accessLevel: "Employee",
    department: "Marketing",
    downloads: 23,
    views: 67,
    shared: false,
  },
  {
    id: 3,
    name: "Budget_Analysis.xlsx",
    type: "spreadsheet",
    size: "845 KB",
    uploadedBy: "Mike Wilson",
    uploadDate: "2025-07-19",
    accessLevel: "Officer",
    department: "Finance",
    downloads: 12,
    views: 34,
    shared: true,
  },
  {
    id: 4,
    name: "Team_Photo_2024.jpg",
    type: "image",
    size: "3.2 MB",
    uploadedBy: "HR Department",
    uploadDate: "2025-07-05",
    accessLevel: "Employee",
    department: "HR",
    downloads: 89,
    views: 203,
    shared: true,
  },
];

export const departments = [
  "Departemen Produksi",
  "Departemen Pemeliharaan (Maintenance)",
  "Departemen Kesehatan, Keselamatan Kerja dan Lingkungan (K3LH)",
  "Departemen Pemasaran dan Penjualan",
  "Departemen Logistik dan Distribusi",
  "Departemen Riset dan Pengembangan (R&D)",
  "Departemen Keuangan dan Akuntansi",
  "Departemen Sumber Daya Manusia (SDM) dan Umum",
  "Departemen Teknologi Informasi (TI/IT)",
];
